### ISSUE TITLE
css3-conditional should be css-conditional

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#11]
From https://github.com/web-platform-tests/wpt/pull/11868#issuecomment-406253602

Scrape should be from the non-levelled https://drafts.csswg.org/css-conditional/, and filename should stay as css-conditional.

cc @gsnedders

**Comment by tidoust** [comment]
Reffy starts from `/TR/` URLs when they exist, retrieves the URL of the Editor's Draft (ED) from the W3C API, and crawls the spec at that URL.

In this case, the starting URL is `https://www.w3.org/TR/css3-conditional/`, the W3C API returns `https://drafts.csswg.org/css-conditional-3/` as the URL of the ED, and thus Reffy crawls the leveled draft. The corresponding folder is named [`css-conditional-3`](https://github.com/w3c/csswg-drafts/tree/master/css-conditional-3) in the CSS repo, so using the leveled URL makes sense to me (the result is the same in any case, both URLs return the same spec).

Whatever draft Reffy crawls, this is not going to change the name of the IDL file. As explained around https://github.com/tidoust/reffy-reports/issues/3#issuecomment-390110815, for better or worse, the IDL file is named from the `/TR/` shortname, which is `css3-conditional`. We automatically get rid of the level when we find it at the end of the URL, but we did not create a custom rule for `css3-` specs to get rid of the `3`. I don't really see a situation where dropping that `3` would be a problem so happy to create such a rule.

**Comment by lukebjerring** [comment]
SGTM (and thanks for the explanation). @gsnedders you happy with that?

**Comment by gsnedders** [comment]
>  I don't really see a situation where dropping that 3 would be a problem so happy to create such a rule.

FWIW, this is mostly just a legacy thing and it shows that css-conditional-3 hasn't been republished in a long time.

As for the ED URL being levelled, can one of you file a bug in w3c/csswg-drafts about that, given I'm about to go to bed? It should be consistent with everything else in the repo and be unversioned.

**Comment by foolip** [comment]
FWIW, in a similar effort of turning URLs into IDs, in https://github.com/foolip/day-to-day/blob/d336df7d08d57204a68877ec51866992ea78e7a2/build/specs.js#L176 I found it necessary to replace "css3" with "css", with one unfortunately exception to the rule with css3-background vs. css-backgrounds. As you can guess from the "no versions thanks" comment, I'd like it if there were no versions, and it looks like this is the only outlier.

**Comment by tidoust** [comment]
Reffy should now create a `css-conditional.idl` file and I changed the name of the file in the repo. Closing this issue accordingly.

Note that the URL of the ED that appears in the `css-conditional.idl` file in comment is still the leveled one. That won't get updated until the CSS WG adopts a consistent non-leveled-ED-URL approach, and until the URL returned by the W3C API for that particular spec gets updated (it typically would if a new version of the spec gets published).

**Comment by gsnedders** [comment]
> That won't get updated until the CSS WG adopts a consistent non-leveled-ED-URL approach

FWIW, this was done years ago, this is just a consequence of that spec not having been republished since 2013.

I wonder if it's worthwhile having the W3C API return an unversioned string for every spec?
