### ISSUE TITLE
Send an alert when the list of IDL files changes

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy-reports#12]
Addition/Removal of IDL files to the reports is manual for now. This is mostly on purpose: we don't want to delete IDL files because of a transient network or other error that would make Reffy crash on a given spec.

Given that the list of IDL files crawled by Reffy is also maintained manually, the list of IDL changes is unlikely going to change without human intervention in any case. But then, that does happen, see #10.

Without necessarily changing the logic in place, it would be good to send an alert one way or the other when new IDL files are detected that are not yet tracked in `reffy-reports` or when the crawl fails to generate an IDL file that is being tracked in `reffy-reports`.

**Comment by dontcallmedom** [comment]
I believe this was overtaken by https://github.com/tidoust/reffy-reports/pull/39/files#diff-4afa3ab9b172c04f043da226e6b1ecdfR42 which adds new IDL files as they appear, so closing
