### ISSUE TITLE
Link to this project in the boilerplate of extracted IDL

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#16]
To resolve https://github.com/web-platform-tests/wpt/issues/11109, it would be great if the boilerplate included a reference to the tooling that did the extracting, namely this repo. In the README.md, we could then perhaps also mention its use in wpt, and link to wpt/interfaces/README.md, so that it's easy for everyone to work out how the changes trickle into wpt.

**Comment by tidoust** [comment]
I'm wondering what text to write to keep things short and informative. Taking inspiration from the wpt readme, would the following (which would only link to this repo, and not to Reffy, to keep the number of URLs minimal) do the trick?

```
// GENERATED CONTENT - DO NOT EDIT
// Content of this file was automatically extracted from the [spec title] spec
// by Reffy into reffy-reports (https://github.com/tidoust/reffy-reports)
// Spec URL: [https://link.to.spec]
```

Now, I see your comment in https://github.com/web-platform-tests/wpt/issues/11109#issuecomment-411402258. I'm fine either way.

**Comment by foolip** [comment]
That actually looks great to me, it doesn't seem weird to name the repo itself when Reffy is also involved. If that change is made, I'll make sure to get them imported into wpt as a bulk PR and not lots of individual ones.

**Comment by foolip** [comment]
Now fixed!
