### ISSUE TITLE
Daily update didn't happen this morning

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#18]
I was monitoring for the changes in https://github.com/tidoust/reffy/commit/cadc77757bf510519ef1bcb2cea213aae4181731 to take effect this morning, as it seems previous commits by @dontcallmedom have been at a regular interval. Today the update didn't happen. Last commit was https://github.com/tidoust/reffy-reports/commit/39f5e00db8c7d915d6651840cd4275edf38a6d27.

I can't tell if this is running as a Travis cron job or something else, so can't help diagnose any further that that :)

@tidoust @dontcallmedom

**Comment by foolip** [comment]
It would be good to have https://github.com/tidoust/reffy/pull/114 merged before the next run though.

**Comment by dontcallmedom** [comment]
daily updated unstuck
