### ISSUE TITLE
No IDL for dom.spec.whatwg.org

### ISSUE THREAD

**Issue by domenic** [tidoust/reffy-reports#35]
This seems kind of bad. We were hoping to use reffy-reports's crawl.json in a tool we're building to get a list of all globals defined by specs, but this is a pretty basic hole...

/cc @jackbsteinberg

**Comment by foolip** [comment]
Here it is: https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/dom.idl

**Comment by tidoust** [comment]
@foolip, the IDL extract is correct but Reffy does not manage to parse that IDL properly for some reason, and thus fails to include the result of that parsing in `crawl.json`, which I believe is what @domenic is interested in.

**Comment by tidoust** [comment]
I believe I fixed the issue in Reffy's code. Fix should appear in reffy-report tomorrow.

This was due to a change in the internal structure produced by `webidl2.js`. This may affect other parts of Reffy's code. Ping @dontcallmedom

**Comment by domenic** [comment]
This is showing up in crawl.json now!
