### ISSUE TITLE
Ensure trailing newline in IDL files

### ISSUE THREAD

**Issue by foolip** [tidoust/reffy-reports#4]
In https://github.com/web-platform-tests/wpt/pull/9837 one can see that there's a missing newline at the end of the file, and this seems to be the case for all of https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl.

Including that missing newline will:
 * stop git from complaining on command line and GitHub on web UI
 * look right if you `cat` a file on the command line (which I do a lot)

**Comment by tidoust** [comment]
@foolip Reffy now adds a trailing newline and all IDL files in the report have been updated accordingly. Closing the issue as a result. Just reopen if I missed something.
