### ISSUE TITLE
webrtc-identity spec is missing

### ISSUE THREAD

**Issue by Pehrsons** [tidoust/reffy-reports#42]
Spec: https://www.w3.org/TR/webrtc-identity/

I see it appearing in crawled links, but it appears to be missing from the list of specs to crawl.

**Comment by foolip** [comment]
@tidoust

**Comment by tidoust** [comment]
Thanks for reporting the missing spec. Now fixed:
- Spec added to the list of specs to crawl in https://github.com/tidoust/reffy/commit/5414c43af99852c5b9dd228f01d7bb5a8730863e
- New crawl report has just been generated and now includes the spec (see [extracted WebIDL](https://github.com/tidoust/reffy-reports/blob/master/ed/idl/webrtc-identity.idl))
- [PR #19292](https://github.com/web-platform-tests/wpt/pull/19292) automatically generated to add the IDL to Web Platform Tests
