### ISSUE TITLE
Add Origin Policy to reffy

### ISSUE THREAD

**Issue by domenic** [tidoust/reffy-reports#45]
I'd like to add an idlharness.js test, and it seems like the first step is to get an auto-generated file into WPT's interfaces/ folder.

https://wicg.github.io/origin-policy/ is the spec in question.

**Comment by tidoust** [comment]
I just added Origin Policy to the list of specs to crawl. It should automatically appear in the report next time the crawl runs (in 3 hours from now), and in Web Platform Tests as a pull request.
