### ISSUE TITLE
subresource-integrity missing?

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#6]
Can't see a scrape of `subresource-integrity` IDL anywhere under `whatwg`.
Spec: https://w3c.github.io/webappsec-subresource-integrity/

**Comment by tidoust** [comment]
That's one of these specs where the shortname used in the published spec is different from the repo name. Shortname of the published spec is `SRI`, so that's the name of the IDL file generated: [`SRI.idl`](https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/SRI.idl)

**Comment by lukebjerring** [comment]
Ah, my bad. I did try search by the content but obviously did a bad job. Thanks!
