### ISSUE TITLE
pointerevents-extension is missing

### ISSUE THREAD

**Issue by lukebjerring** [tidoust/reffy-reports#9]
Defined here:
https://w3c.github.io/pointerevents/extension.html

I noticed `pointerevents-extension.idl` and its tests while authoring https://github.com/web-platform-tests/wpt/pull/11922

**Comment by tidoust** [comment]
Now added to the report in [`pointerevents-extension.idl`](https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/pointerevents-extension.idl)
